"""Initial migration

Revision ID: 97477c89b8c6
Revises: 
Create Date: 2025-10-12 22:18:22.166786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97477c89b8c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_achievement_sort_order'), ['sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievement_sort_order'))
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
